### ISSUE TITLE
如何配置和一些问题

### ISSUE THREAD

**Issue by p308715744** [xsank/Shour#4]
你好

对你的这个程序很感兴趣，希望能测试体验下
由于对java框架不熟悉，我使用的intellij idea加载的项目
经处理后，
\src\main\java\org\nerdboy\chatbot\server\QAServer.java
server.setHandler(context);
提示错误
cannot access attribute ，也就是没有setHandler方法
我不清楚是不是maven依赖的问题，还是其他的问题

再有就是启动的问题，
我配置使用了tomcat，deployment配置 选择了webapp目录
浏览器
http://localhost:8080/shour?question=%E4%BD%A0%E5%A5%BD
提示

HTTP Status 404 - /shour
type Status report
message /shour
description The requested resource is not available.

不胜感谢

**Comment by p308715744** [comment]
没发现主函数呢?怎么运行，idea也没找到运行的按钮。。。
不好意思，真小白

**Comment by xsank** [comment]
@p308715744 ,如果你也用idea的话打开很方便的
主体就是Shour了，简单建立一个main类也行，不过你直接执行ShourTest就行了
由于当时一时兴起，也没仔细整理下，很抱歉引起了一些不便

**Comment by neconano** [comment]
感谢你的回复，使用后发现，如果提问的内容稍微多两个字后就不能识别，这块有没有优化后的方案，或者有没有其他的成熟样例，感谢分享

**Comment by xsank** [comment]
@neconano ,这个是简单的问答机器人，其中问答的实现是通过去除语义无关词性然后进行trie树检索的，所以在问题识别上明显会弱于语义相似度分析
另外当时用colenlp本来想实现多语言，但发现其实它对于中文支持并不是很好（比如中文同义词分析），所以建议你参考下思路即可，库可以换成专门针对中文的

**Comment by neconano** [comment]
好的，3q
