### ISSUE TITLE
请问Shour这个类是在哪初始化的呢？

### ISSUE THREAD

**Issue by chenfeng1993** [xsank/Shour#5]
QAServlet 这个类里面声明Shour之后就直接调用它的接口了，现在报一个空指针的错误，请问下Shour这个类应该在什么时机初始化呢？

**Comment by xsank** [comment]
抱歉哈，你想看效果的话直接执行ShourTest吧，也可以自行改下Shour，加一个main

**Comment by xsank** [comment]
避免用户疑惑，已在Shour中添加入口
